HUDHealthcarePortal/Controllers/OPAForm/OPAFormController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using System.Windows.Forms;
using BusinessService.Interfaces;
using Elmah;
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.BusinessService.Interfaces;
using HUDHealthcarePortal.BusinessService.ProjectAction;
using HUDHealthcarePortal.Core;
using HUDHealthcarePortal.Core.Utilities;
using HUDHealthcarePortal.Helpers;
using HUDHealthcarePortal.Model;
using HUDHealthcarePortal.Model.ProjectAction;
using BusinessService.ProjectAction;
using HUDHealthCarePortal.Helpers;
using Model.ProjectAction;
using MvcSiteMapProvider;
using MvcSiteMapProvider.Web.Mvc.Filters;
using WebGrease.Css.Extensions;
using BusinessService.AssetManagement;
using BusinessService;
using Model;
//using BusinessService.Interfaces.Production;
using BusinessService.Production;
using Model.Production;
using System.Net;// User Story 1901
using Repository.Interfaces;
using Repository;
using System.Configuration;
using Newtonsoft.Json.Linq;
using BusinessService.Interfaces.Production;
using BusinessService.ManagementReport;
using System.Collections;
using HUDHealthcarePortal.Repository.Interfaces;
//using HUDHealthcarePortal.Repository;

namespace HUDHealthcarePortal.Controllers.OPAForm
{
    public class OPAFormController : Controller
    {

        private IProjectActionFormManager projectActionFormManager;
        private IProjectActionManager projectActionManager;
        private IGroupTaskManager groupTaskManager;
        private ITaskManager taskManager;
        private ISubFolderStructureRepository folderManager;
        private IAccountManager accountManager;
        private IEmailManager emailManager;
        private IBackgroundJobMgr backgroundJobManager;
        private INonCriticalRepairsRequestManager nonCriticalRepairsManager; // User Story 1901
        private IParentChildTaskManager parentChildTaskManager;
        private IRequestAdditionalInfoFileManager requestAdditionalInfoFilesManager;
        private IReviewFileStatusManager reviewFileStatusManager;
        private IProd_RestfulWebApiDownload WebApiDownload;
        private IProd_RestfulWebApiUpdate WebApiUpdate;
        private IProd_RestfulWebApiDelete WebApiDelete;
        private IProd_RestfulWebApiTokenRequest WebApiTokenRequest;
        private IProd_RestfulWebApiDocumentUpload WebApiDocumentUpload;
        private IProd_RestfulWebApiReplace WebApiDocumentReplace;
        private IProd_GroupTasksManager prod_GroupTasksManager;
        private IOPAManager iOPAForm;
        IWebSecurityWrapper webSecurity;
        private IAppProcessManager appProcessManager;
        private string DefaultDocID = ConfigurationManager.AppSettings["DefaultDocId"].ToString();
        private ITaskFile_FolderMappingManager taskFile_FolderMappingManager;
        private IProd_NextStageManager prod_NextStageManager;
        IPAMReportManager _plmReportMgr;
        private IProd_RestfulWebApiUpdate prodRestfulWebApiUpdate;
        //#605
        private IProd_TaskXrefManager prod_TaskXrefManager;
        //#605
        private IProductionQueueManager productionQueue;
        //#605
        private readonly ILookupManager lookupMgr;
        private IFHANumberRequestManager fhaRequestManager;
        private IProd_SharepointScreenManager sharepointScreenManager;


        //
        // GET: /OPAForm/

        public OPAFormController()
            : this(
                new ProjectActionFormManager(), new TaskManager(), new AccountManager(), new EmailManager(),
                new BackgroundJobMgr(), new ProjectActionManager(), new GroupTaskManager(),
                new NonCriticalRepairsRequestManager(), new ParentChildTaskManager(),
                new RequestAdditionalInfoFilesManager(), new ReviewFileStatusManager(), new WebSecurityWrapper(), new OPAManager(),
                new Prod_RestfulWebApiDownload(), new Prod_RestfulWebApiTokenRequest(), new Prod_RestfulWebApiUpdate(),
                new Prod_RestfulWebApiDocumentUpload(), new Prod_RestfulWebApiReplace(), new Prod_RestfulWebApiDelete(), new SubFolderStructureRepository(), new Prod_GroupTasksManager(), new AppProcessManager()
                   , new TaskFile_FolderMappingManager(), new Prod_NextStageManager(), new PAMReportsManager(), new Prod_RestfulWebApiUpdate(), new Prod_TaskXrefManager()
                 , new ProductionQueueManager(), new LookupManager(), new FHANumberRequestManager(), new Prod_SharepointScreenManager())

        {
        }

        private OPAFormController(IProjectActionFormManager _projectActionFormManager, ITaskManager _taskManager,
            IAccountManager _accountManager, IEmailManager _emailManager, IBackgroundJobMgr backgroundManager,
            IProjectActionManager _projectActionManager, IGroupTaskManager _groupTaskManager,
            INonCriticalRepairsRequestManager _nonCriticalRepairsManager,
            IParentChildTaskManager _parentChildTaskManager,
            IRequestAdditionalInfoFileManager _requestAdditionalInfoFilesManager,


            IReviewFileStatusManager _reviewFileStatusManager,
            IWebSecurityWrapper webSec,
            IOPAManager _opaManager,
            IProd_RestfulWebApiDownload _WebApiDownload,
            IProd_RestfulWebApiTokenRequest _WebApiTokenRequest,
            IProd_RestfulWebApiUpdate _WebApiUpdate,
            IProd_RestfulWebApiDocumentUpload _WebApiDocumentUpload,
            IProd_RestfulWebApiReplace _WebApiDocumentReplace,
            IProd_RestfulWebApiDelete _WebApiDelete,
            ISubFolderStructureRepository _folderManager,
            IProd_GroupTasksManager _prod_GroupTasksManager,
            IAppProcessManager _AppProcessManager, ITaskFile_FolderMappingManager _taskFile_FolderMappingManager,//harish added
              IProd_NextStageManager _prod_NextStageManager, IPAMReportManager plmReportMgr, IProd_RestfulWebApiUpdate _prodRestfulWebApiUpdate, IProd_TaskXrefManager _prodTaskXrefManager
            , IProductionQueueManager _productionQueueManager, ILookupManager _lookupMgr,
             FHANumberRequestManager _fhaRequestManager, IProd_SharepointScreenManager _sharepointScreenManager)
        {
            projectActionFormManager = _projectActionFormManager;//harish added
            taskFile_FolderMappingManager = _taskFile_FolderMappingManager;//harish added
            taskManager = _taskManager;
            accountManager = _accountManager;
            emailManager = _emailManager;
            backgroundJobManager = backgroundManager;
            projectActionManager = _projectActionManager;
            groupTaskManager = _groupTaskManager;
            nonCriticalRepairsManager = _nonCriticalRepairsManager; // User Story 1901
            parentChildTaskManager = _parentChildTaskManager;
            requestAdditionalInfoFilesManager = _requestAdditionalInfoFilesManager;
            reviewFileStatusManager = _reviewFileStatusManager;
            nonCriticalRepairsManager = _nonCriticalRepairsManager;// User Story 1901
            webSecurity = webSec;
            iOPAForm = _opaManager;
            WebApiDownload = _WebApiDownload;
            WebApiTokenRequest = _WebApiTokenRequest;
            WebApiUpdate = _WebApiUpdate;
            WebApiDelete = _WebApiDelete;
            WebApiDocumentUpload = _WebApiDocumentUpload;
            WebApiDocumentReplace = _WebApiDocumentReplace;
            folderManager = _folderManager;
            prod_GroupTasksManager = _prod_GroupTasksManager;
            appProcessManager = _AppProcessManager;
            prod_NextStageManager = _prod_NextStageManager;
            _plmReportMgr = plmReportMgr;
            prodRestfulWebApiUpdate = _prodRestfulWebApiUpdate;
            prod_TaskXrefManager = _prodTaskXrefManager;
            productionQueue = _productionQueueManager;
            lookupMgr = _lookupMgr;
            fhaRequestManager = _fhaRequestManager;
            sharepointScreenManager = _sharepointScreenManager;
        }



        [OutputCache(NoStore = true, Duration = 0, VaryByParam = "*")]
        // [MvcSiteMapNode(Title = "Project Action Request Form", ParentKey = "AMId", PreservedRouteParameters = "", Key = "OPAkey")]
        [MvcSiteMapNode(Title = "Project Action Request Form", ParentKey = "AMId")]
        [SiteMapTitle("PAMReport", Target = AttributeTarget.CurrentNode)]
        public ActionResult Index()
        {
            OPAViewModel OPAprojectActionViewModel = new OPAViewModel();
            InitializeViewModel(OPAprojectActionViewModel);
            //OPAWorkProduct(OPAprojectActionViewModel.PropertyWorkProduct.TaskInstanceId);
            return View("~/Views/OPAForm/OPARequestForm.cshtml", OPAprojectActionViewModel);
        }

        // to attach a form for AE
        public void OPAWorkProduct(Guid taskInstanceId, string fileType)
        {
            //List<OPAWorkProductModel> OPAprojectActionViewModel = iOPAForm.getAllOPAWorkProducts(taskInstanceId, fileType);
            List<OPAWorkProductModel> OPAprojectActionViewModel = iOPAForm.getAllOPAWorkProducts(taskInstanceId, fileType);
            //return PartialView("~/Views/OPAForm/_OPAUploadForAe.cshtml", OPAprojectActionViewModel);
        }

        public JsonResult GetOPAWorkProduct(string sidx, string sord, int page, int rows, Guid taskInstanceId, string fileType)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;

            var opaWorkProduct = iOPAForm.getAllOPAWorkProducts(taskInstanceId, fileType);

            //Setting the date based on the Time Zone
            if (opaWorkProduct != null)
            {
                foreach (var item in opaWorkProduct)
                {

HUDHealthcarePortal/Views/OPAForm/ConfirmPopup.cshtml
<script type="text/javascript">
    function userSelected(target) {
        $('#dialogCommon').dialog('close');

        if ($(target).val() == 'Ok') {
             if (requestStatus == '2' || requestStatus == '3')
                $('#btnSubmit').click();
        }
        else {
            $("#txtPopup").val(false);
        }
        return false;
    }
</script>
<div class="container-fluid">
    <div class="row" style="margin-top:20px;">
        <div>
            <p></p>

       
            @if ((string)TempData["RequesStatus"] == "Save")
            {
                <p>Your application was saved successfully.</p>
                TempData["RequesStatus"] = "";
            }
            else if ((string)TempData["RequesStatus"] == "Checkin")
            {
                <p>Please verify the data before approving/denying this request.</p>
            }

        </div>
    </div>

    <br />

    <div class="row" style="margin-left:150px;">
        <span class="col-md-2">
            <input id="btnOk" type="submit" name="agreeOrNot" class="form-control" value="Ok" onclick="userSelected(this)">
        </span>
         @*@if ((int)TempData["RequesStatus"] == 2 || (int)TempData["RequesStatus"] == 3)
         {
            <span class="col-md-2" style="margin-left:10px;">
                <input id="btnCancel" type="submit" name="agreeOrNot" class="form-control" value="Cancel" onclick="userSelected(this)">
            </span>
         }*@
    </div>
</div>
<script>
    //var requestStatus = '@TempData["RequesStatus"]';
</script>

HUDHealthcarePortal/Views/OPAForm/_OPAAttachFinalWorkProducts.cshtml
@model HUDHealthcarePortal.Model.OPAViewModel

<style>
    .fileClass {
        width: 100px !important;
        padding: 5px !important;
    }
</style>
<link href="~/Content/ui.jqgrid.css" rel="stylesheet" />
@*<script src="~/Scripts/free-jqGrid/jquery-1.9.1.min.js"></script>*@
@*<script src="~/Scripts/jquery-1.9.1.min.js"></script>*@
<script src="~/Scripts/free-jqGrid/jquery.jqGrid.min.js"></script>

<link href="~/Content/themes/redmond/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<script type="text/javascript" src="~/Content/themes/redmond/jquery-ui-1.12.1.custom/jquery-ui.js"></script>

<div id="FinalWorkProductDiv" style="width:700px">
    <table id="TaskGridLender"></table>
    <div id="Finalopapager"></div>
</div>



<script>
   
    function handleDeleteFile(id) {      
        //  debugger;
        var childFileId = id;
        $("#spinner").attr('class', 'overlay');
        $.ajax({
            type: "POST",
            url: "/OPAForm/OPADeletefile/?taskfileid=" + childFileId,

            contentType: false,
            processData: false,
            cache: false,
            success: function (result) {
                //    debugger;
                if (result === "Success") {
                    alert("File Deleted Successfully");
                    jQuery('#TaskGridLender').trigger('reloadGrid');
                    jQuery('#opacontent').trigger('reloadGrid');
                }
            },
            error: function (xhr, status, p3, p4) {
                //  debugger;
                var err = "Error " + " " + status + " " + p3 + " " + p4;
                if (xhr.responseText && xhr.responseText[0] == "{")
                    err = JSON.parse(xhr.responseText).Message;
                console.log(err);
            }
        });
    }

</script>

<script>
    $(document).ready(
        function () {
            // debugger;
            $("#TaskGridLender").jqGrid({
                url: "/OPAForm/GetOPAWorkInternalProduct?taskInstanceId=" + "@Model.TaskInstanceId" ,
               //url: "/OPAForm/GetOPAWorkProduct?taskInstanceId=" + $("#TaskGuid").val() + "&fileType=" + "FWP" + "",
                datatype: 'json',
                mtype: 'POST',

                colNames: ['File Name', 'File Size(KB)', 'Role','Uploaded By', 'Uploaded On', 'Remove Attachment'],
                colModel: [

                    {
                        Key: false, name: 'FileName', index: 'FileName', width: 250, type: 'link',
                        cellattr: function (cellvalue, options, rowObject) {
                            if (rowObject.FileName != null) {

                                return ' style="text-decoration: underline"';
                            }
                        },
                        formatter: function (cellvalue, options, rowObject) {

                            if (rowObject.FileName == null) {
                                return "NA"
                            }
                            else {

                                return '<a href="/OPAForm/DownloadTaskFile/?taskfileid=' + rowObject.FileId + '">' + rowObject.FileName + '</a>';
                            }
                        }
                    },

                    {
                        name: 'FileSize', index: 'FileSize', editable: false, width: 200,
                    },
                    { Key: false, name: 'RoleName', index: 'RoleName', editable: false, width: 200 },
                    { Key: false, name: 'UploadedBy', index: 'UploadedBy', editable: false, width: 200 },
                    { Key: false, name: 'UploadTime', index: 'UploadTime', editable: true, width: 250, formatter: 'date', formatoptions: { newformat: 'm/d/Y h:i A' }, sorttype: "date" },

                    {
                        Key: false, name: 'FileId', index: 'FileId', width: 150, sortable: false,
                        formatter: function (cellvalue, options, rowObject) {

                            if (rowObject.FileName == null) {
                                return "NA"
                            }
                            else {
                                //return '   <input id="' + rowObject.fileId + '" type=\'button\' value=\'Delete\' class=\'deleteLinkClass\'    />';
                                return "<img src='/Content/images/delete.jpg' id='" + rowObject.FileId + "' height='10' width='10' align='center' alt='my image' value=\'Delete\' class=\'deleteLinkClass\' />";
                            }
                        },
                        formatoptions: {
                            keys: true,
                            editformbutton: true
                        }

                    },
                ],
                pager: jQuery('#Finalopapager'),
                cellEdit: false,
                cellsubmit: 'clientArray',
                rowNum: 10,
                //loadonce: true,
                rowList: [10, 20, 30, 40],
                shrinkToFit: false,
                height: '100%',
                viewrecords: true,
                gridview: true, autoencode: true,
                width: 1250,

                emptyrecords: 'No records to display',
                jsonReader: {
                    root: "rows",
                    page: "page",
                    total: "total",
                    records: "records",
                    repeatitems: false
                },

                loadComplete: function (data) {
                    // debugger;
                    if (@Model.RequestStatus == 2)
                    {

                        jQuery("#TaskGridLender").jqGrid('hideCol', 'FileId');
                        jQuery("#TaskGridLender").setGridWidth('1100');
                    }

                    if (@Model.RequestStatus == 1 && @Model.columnVisibility == 1)
                    {

                        jQuery("#TaskGridLender").jqGrid('hideCol', 'FileId');
                        jQuery("#TaskGridLender").setGridWidth('1100');
                    }


                },
                //autowidth: true,
                multiselect: false,

                beforeSelectRow: function (rowid, e) {

                    // debugger;
                    var $self = $(this),
                        p = $self.jqGrid("getGridParam"),
                        $td = $(e.target).closest("tr.jqgrow>td"),
                        cm = $td.length > 0 ? p.colModel[$td[0].cellIndex] : null,
                        cmName = cm != null ? cm.name : null;

                    if (cmName === "FileId") {
                        handleDeleteFile(e.target.id);
                        //var deleteElements = document.getElementsByClassName('deleteLinkClass');
                        //for (var i = 0; i < deleteElements.length; i++) {
                        //    //alert(deleteElements[i].id);
                        //    deleteElements[i].addEventListener('click',
                        //        handleDeleteFile, false);

                        //}

                    }

                    return false;
                },
                gridComplete: function () {

                },

                //loadComplete: function () {

                //},
                loadError: function (xhr, status, error) {

                },
                multiselect: false,
                autoencode: true,

            }).navGrid('#pager', { edit: false, add: false, del: false, search: false, refresh: false });

        });

    function Removefile(taskFileId, groupTaskInstanceId) {

        $("#spinner").attr('class', 'overlay');
        $.ajax({
            url: '/OPAForm/OPARemovefile/TaskGuid?=' + $('#TaskGuid').val(),
            data: {
                taskInstanceId: groupTaskInstanceId,
                taskFileId: taskFileId,
                OPAProjectActionViewModel: '@Model',
                TaskGuid: TaskGuid,
                lendercomment: lendercomment


            },
            cache: false,
            type: 'POST',
            success: function (response) {
                // debugger;

                $("#paformreadonly").html("");
                $("#paformreadonly").html(response);
                $("#paform").html("");
                $("#paform").html(response);
                alert('File successfully deleted');
                $("h4:first").html('');

                $("#isAgreementRequiredErrorMessage").hide();




            },
            error: function (xhr) {
                // TODO: alert the user about the error
            }
        });


    }
</script>

HUDHealthcarePortal/Views/OPAForm/_OPAFinalWorkProductsUploadCheckList.cshtml
@model OPAViewModel
<script src="~/Scripts/jquery-ui-1.9.2.min.js"></script>
<script src="/Scripts/jquery.fileupload.js"></script>
<script src="/Scripts/jquery.fileupload-ui.js"></script>
<script src="/Scripts/jquery.iframe-transport.js"></script>





<style>
    .specialContainer {
        display: inline-block;
        vertical-align: top;
        -moz-box-sizing: border-box;
        -webkit-box-sizing: border-box;
        box-sizing: border-box;
    }

    #hold {
        display: block;
        padding: 10px 10px;
        width: 100%;
        max-height: 600px;
    }

    table#myDemoTable {
        width: 100%;
        max-height: 100%;
        border-collapse: collapse;
        border-spacing: 0;
        background: white;
        overflow-y: scroll;
        height: 600px;
        display: block;
    }

    .content,
    .header,
    .container {
        width: 100%;
        max-height: 100%;
    }


    .header {
        color: black;
        text-align: center;
    }

    .container {
        background: white;
    }

    .sidebar {
        width: 10%;
        background: white;
        color: white;
        float: left;
    }

    .content {
        width: 90%;
        position: relative;
    }

    h4 {
        margin: 0;
    }

    #myDemoTable table {
    }

    #myDemoTable thead {
        position: absolute;
        top: 1px;
        left: 0px;
        right: 0px;
    }

    #myDemoTable tbody {
        padding: 1.3em 0px 0px;
        margin: 0px;
        display: block;
    }

    #myDemoTable tr {
        width: 100%;
        display: block;
        margin-top: -2px;
    }

    #myDemoTable th {
        position: absolute;
    }

    #myDemoTable td {
        display: inline-block;
        margin: 0px;
        padding: 0px;
    }

    td.col2,
    td.col3,
    td.col4,
    td.col5 {
        margin-left: -4px;
    }

    .col1 {
        width: 60%;
    }

    .col2 {
        width: 12%;
    }

    .col3 {
        width: 12%;
    }

    .col4 {
        width: 12%;
    }



    #myDemoTable a {
        display: block;
        width: 75px;
    }

    .fileClass {
        width: 75px !important;
        padding: 5px !important;
    }


    /*!
       * Helpers to hide text field in type = "file", and present buttons consistently.
       */

    /* Hide the file input using opacity */
    [type=file] {
        position: absolute;
        filter: alpha(opacity=0);
        opacity: 0;
        top: -100px;
    }

        [type=file] + label {
            font-weight: bold;
            border: 1px solid #CCC;
            border-radius: 3px;
            text-align: left;
            padding: 10px;
            margin: 0;
            left: 0;
            position: relative;
        }

        [type=file] + label {
            font-weight: bold;
            text-align: center;
            border-radius: 3px;
            left: 0em;
            top: 0.5em;
            /* Decorative */
            background: #333;
            color: #fff;
            border: none;
            cursor: pointer;
        }

            [type=file] + label:hover {
                background: #3399ff;
            }

    [type=button] {
        border: 1px solid #CCC;
        border-radius: 3px;
        text-align: left;
        padding: 10px;
        width: 75px;
        margin: 0;
        left: 0;
        position: relative;
    }

    [type=button] {
        border: 1px solid #CCC;
        border-radius: 3px;
        text-align: center;
        font-weight: bold;
        left: 0em;
        top: 0.5em;
        /* Decorative */
        background: #333;
        color: #fff;
        border: none;
        width: 75px;
        cursor: pointer;
    }

    #myDemoTable a {
        border: 1px solid #CCC;
        border-radius: 3px;
        text-align: left;
        padding: 10px;
        width: 75px;
        margin: 0;
        left: 0;
        position: relative;
        text-decoration: none;
    }

    #myDemoTable a {
        text-align: center;
        font-weight: bold;
        left: 0em;
        top: 0.5em;
        /* Decorative */
        background: #333;
        color: #fff;
        border: none;
        cursor: pointer;
        width: 75px;
        text-decoration: none;
        width: 20em;
        height: 2em;
    }


    #divSideBar a {
        border: 1px solid #CCC;
        border-radius: 3px;
        text-align: left;
        padding: 10px;
        width: 75px;
        margin: 0;
        left: 0;
        position: relative;
        text-decoration: none;
    }

    #divSideBar a {
        text-align: center;
        font-weight: bold;
        left: 0em;
        top: 0.5em;
        /* Decorative */
        background: #333;
        color: #fff;
        border: none;
        cursor: pointer;
        width: 75px;
        text-decoration: none;
        width: 20em;
        height: 2em;
    }

        #divSideBar a:hover {
            background: #3399ff;
        }


    [type=button]:hover {
        background: #3399ff;
    }

    #myDemoTable a:hover {
        background: #3399ff;
    }
</style>
@using (Html.BeginForm("OPAuploadOpaFiles", "OPAForm", FormMethod.Post, new { enctype = "multipart/form-data", style = "margin:auto;", id = "OPAChecklist" }))
{


    <div class="container-fluid">
        <div class="row">
            @if (Model.RequestStatus == 2)
            {
                <span class="col-md-4 text-right vbottom">
        @Html.Label("HUD Initiated Documents")
    </span>

            }
            else if (Model.RequestStatus == 5)
            {
                <span class="col-md-4 text-right vbottom">
                    @Html.Label("HUD Initiated Documents")
                </span>

            }


            @if (Model.RequestStatus == 1)
            {
                <span class="col-md-4 text-right vbottom">
        @Html.Label("Upload HUD Initiated Documents")
    </span>
                <span class="col-md-4">

                   
                    <input class="fileClass" id="btn_workproduct" name="btn_workproduct" type="file" value="" multiple="multiple">
                    <label id="btn_workproduct" for="btn_workproduct" class="fileClass"><strong> Attach </strong></label>
                    
                </span>
            }
        </div>

    </div>
 
  

}

HUDHealthcarePortal/Views/OPAForm/_OpaWorkProductAEView.cshtml
@model HUDHealthcarePortal.Model.OPAViewModel
@{
    Layout = null;
}

<div class="container-fluid" style="padding-top: 15px">
    <div class="panel with-nav-tabs panel-primary">
        <div class="panel-heading">
            <ul class="nav nav-tabs">
                <li id="tab1primaryhead" class="active"><a href="#tab1primary" data-toggle="tab">External Products</a></li>
                <li id="tab2primaryhead"><a href="#tab2primary" id="tab2" data-toggle="tab"> Internal Products</a></li>
            </ul>
        </div>
        <div class="panel-body">
            <div class="tab-content">
                <div class="tab-pane fade in active" id="tab1primary">
                    @Html.Partial("~/Views/OPAForm/_OPAAEIntitate.cshtml");

                    @*@Html.Partial("~/Views/Production/_Shared/_HudInitiated.cshtml")*@
                </div>
                <div class="tab-pane fade focus" id="tab2primary">
                    @*@Html.Partial("~/Views/Production/ProductionQueue/AssignedProductionTasks.cshtml")*@

                    @Html.Partial("~/Views/OPAForm/_AEOPAUploadGrid.cshtml", Model)
                </div>
            </div>
        </div>
    </div>
</div>