HUDHealthcarePortal/Controllers/Production/AdhocController.cs
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class AdhocController : Controller
    {
        //
        // GET: /Adhoc/

        public ActionResult Index()
        {
            var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(UserPrincipal.Current.Timezone);
            var reportDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, timeZoneInfo).ToString("MM/dd/yyyy hh:mm:ss tt");
            Session["ReportDate"] = timeZoneInfo.SupportsDaylightSavingTime ? reportDate + " " + TimezoneManager.ShortTimeZoneFormat(timeZoneInfo.DaylightName) 
                : reportDate + " " + TimezoneManager.ShortTimeZoneFormat(timeZoneInfo.StandardName);
            return View("~/Views/Production/Adhoc/Index.cshtml");
        }

    }
}

HUDHealthcarePortal/Controllers/Production/FHARequestNumberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class FHARequestNumberController : Controller
    {
        //
        // GET: /FHARequestNumber/

        public ActionResult Index()
        {
            return View();
        }

    }
}

HUDHealthcarePortal/Controllers/Production/ProductionQueueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using BusinessService.Interfaces;
using BusinessService.Interfaces.Production;
using BusinessService.Production;
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.Core;
using Microsoft.Ajax.Utilities;
using Model;
using Model.Production;
using BusinessService.Interfaces.Production;
using BusinessService.Production;
using Core;
using Core.Utilities;
using HUDHealthcarePortal.Core;
using HUDHealthcarePortal.Core.Utilities;
using HUDHealthcarePortal.Model;
using BusinessService.ProjectAction;
using System.Globalization;
using Rotativa;
using Rotativa.Options;
using System.Net.Http;
using System.IO;
using HUDHealthcarePortal.Helpers;
using Repository.Interfaces;
using System.Configuration;
using System.Collections;
using SpreadsheetGear;
using HUDHealthcarePortal.BusinessService.Interfaces;
//using AutoMapper;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class ProductionQueueController : Controller
    {
        private IProductionQueueManager productionQueue;
        private IProd_TaskXrefManager prod_TaskXrefManager;
        private ITaskManager taskManager;
        private IFHANumberRequestManager fhaNumberRequestManager;
        private IProd_NoteManager prod_noteManager;
        private IAppProcessManager appProcessManager;
        private IProd_ViewManager prodviewmanager;
        private IBackgroundJobMgr backgroundJobManager;
        private IProjectActionFormManager _projectActionFormManager;
        private IProd_SharepointScreenManager sharepointScreenManager;
        private IProd_RestfulWebApiDocumentUpload uploadApiManager;
        private IProd_RestfulWebApiTokenRequest webApiTokenRequest;
        private IProd_RestfulWebApiDownload webApiDownload;
        private IAccountManager accountManager;
        private IProd_LoanCommitteeManager loanCommitteManager;
        //Added by siddu #841 @21042020
        private IParentChildTaskManager _parentChildTaskManager;
        //private ITaskManager _taskManager;
       // private IProd_TaskXrefManager _prodTaskXrefManager;
        string[] authorsList;
        string[] authorsListcompleted;
        string[] apptypearr;
        List<Prod_Taskassigned> lstTasksmain = new List<Prod_Taskassigned>();
        IEnumerable<TaskModel> productionTasks;
        IEnumerable<TaskModel> productionTasksmultiplefilterdata;
        IEnumerable<FilteredProductionTasksModel> productionTasksunasiignedfilter;
        //ArrayList getpagetypeidunassignedsearch = new ArrayList();
        public ProductionQueueController()
            : this(new TaskManager(), new Prod_TaskXrefManager(), new ProductionQueueManager(), new FHANumberRequestManager(), new Prod_NoteManager(), new AppProcessManager(),
            new Prod_ViewManager(), new BackgroundJobMgr(), new ProjectActionFormManager(), new Prod_SharepointScreenManager(), new Prod_RestfulWebApiDocumentUpload(),
            new Prod_RestfulWebApiTokenRequest(), new Prod_RestfulWebApiDownload(), new AccountManager(), new Prod_LoanCommitteeManager(), new ParentChildTaskManager())
        {

        }
        public ProductionQueueController(ITaskManager _taskManager, IProd_TaskXrefManager _prodTaskXrefManager, IProductionQueueManager _productionQueueManager,
                                          IFHANumberRequestManager _fhaNumberRequestManager, IProd_NoteManager _prodNoteManager, IAppProcessManager _appProcessManager,
            IProd_ViewManager _prodviewmanager, IBackgroundJobMgr backgroundManager, IProjectActionFormManager projectActionFormManager,
            IProd_SharepointScreenManager _sharepointScreenManager, IProd_RestfulWebApiDocumentUpload _prod_RestfulWebApiDocumentUpload,
            IProd_RestfulWebApiTokenRequest _prod_WebApiTokenRequest, IProd_RestfulWebApiDownload _webApiDownload, IAccountManager _accountManager,
            IProd_LoanCommitteeManager _loanCommitteeManager, IParentChildTaskManager parentChildTaskManager)
        {

            taskManager = _taskManager;
            prod_TaskXrefManager = _prodTaskXrefManager;
            productionQueue = _productionQueueManager;
            fhaNumberRequestManager = _fhaNumberRequestManager;
            prod_noteManager = _prodNoteManager;
            appProcessManager = _appProcessManager;
            prodviewmanager = _prodviewmanager;
            backgroundJobManager = backgroundManager;
            _projectActionFormManager = projectActionFormManager;
            sharepointScreenManager = _sharepointScreenManager;
            uploadApiManager = _prod_RestfulWebApiDocumentUpload;
            webApiTokenRequest = _prod_WebApiTokenRequest;
            webApiDownload = _webApiDownload;
            accountManager = _accountManager;
            loanCommitteManager = _loanCommitteeManager;
            //Added by siddu #841 @21042020
            _parentChildTaskManager = parentChildTaskManager;
        }
        // GET: /ProductionTask/

        public ActionResult Index()
        {
            //karri#205
            IList<String> SearchableData = getSearchableData(0);//0 mean all types of requests and tasks and projects
            ViewBag.SearchableData = SearchableData;

            //karri#264
            IList<String> AssignedSearchableData = getAssignedSearchableData(0);//0 mean all types of requests and tasks and projects      
            ViewBag.AssignedSearchableData = AssignedSearchableData;
            //karri#264
            IList<String> CompletedSearchableData = getCompletedSearchableData(0);//0 mean all types of requests and tasks and projects
            //ViewData["BindingFHAAndProjName"] = "123456";
            ViewBag.CompletedSearchableData = CompletedSearchableData;

            PopulateLookUps();

            var isHudAdmin = RoleManager.IsHudAdmin(UserPrincipal.Current.UserName);
            if (isHudAdmin)
                return View("~/Views/Production/ProductionQueue/HudAdminReadOnly/ProductionQueueReadOnly.cshtml");
            return View("~/Views/Production/ProductionQueue/Index.cshtml");
        }

        public ActionResult AssignedProductionTasks()
        {
            PopulateLookUps();
            return PartialView("~/Views/Production/ProductionQueue/AssignedProductionTasks.cshtml");
        }

        public ActionResult TaskAsignment(Guid taskXrefid)
        {
            var xrefTask = prod_TaskXrefManager.GetProductionSubtaskById(taskXrefid);
            var taskAssignmentModel = new ProductionTaskAssignmentModel { TaskXrefid = taskXrefid, TaskName = EnumType.GetEnumDescription(EnumType.Parse<ProductionView>(xrefTask.ViewId.ToString())) };
            var curentUser = UserPrincipal.Current.UserName;
            taskAssignmentModel.isWLM = RoleManager.IsProductionWLM(curentUser);
            var productionUser = (from prodUsers in productionQueue.GetProductionUsers()
                                  select new
                                  {
                                      prodUsers.UserID,
                                      Name = String.Format("{0} {1}", prodUsers.FirstName, prodUsers.LastName)

                                  });

            ViewBag.AssignedToUserId = new SelectList(productionUser, "UserID", "Name");
            return View("~/Views/Production/ProductionQueue/TaskAsignment.cshtml", taskAssignmentModel);
        }

        [HttpPost]
        public void UpdateTaskAsignment(ProductionTaskAssignmentModel model)
        {
            var currentUser = UserPrincipal.Current;
            if (currentUser != null)
            {
                if (model != null)
                {
                    model.AssignedToUserId = model.AssignedToUserId;
                    model.CurrentUserId = currentUser.UserId;
                    model.UserName = productionQueue.GetUserById(model.AssignedToUserId).UserName;
                    model.Status = (int)ProductionFhaRequestStatus.InProcess;
                    model.AssignedDate = DateTime.UtcNow;
                    if (model.PageTypeId == (int)PageType.Form290)
                    {
                        model.Status = (int)TaskStep.Form290Request;
                        productionQueue.AssignForm290Task(model);
                    }
                    else
                    {

                        if (model.TaskInstanceId == Guid.Empty)
                            prod_TaskXrefManager.AssignProductionFhaRequest(model);
                        else
                        {
                            productionQueue.AssignProductionFhaInsert(model);
                            //FHANumberRequestViewModel FHANumberRequestViewModel = new FHANumberRequestViewModel();
                            //FHANumberRequestViewModel.TaskinstanceId = model.TaskInstanceId;
                            //fhaNumberRequestManager.UpdateFHARequest(FHANumberRequestViewModel);
                            fhaNumberRequestManager.FhataskAssignedfromQueDateUpdate(model.TaskInstanceId);
                        }

                    }


                }

            }
        }
        public ActionResult FhaInsertAssignment(Guid taskInstanceId)
        {
            var taskAssignmentModel = new ProductionTaskAssignmentModel { TaskInstanceId = taskInstanceId, TaskName = "FHA # Insert" };
            var curentUser = UserPrincipal.Current.UserName;
            taskAssignmentModel.isWLM = RoleManager.IsProductionWLM(curentUser);
            var productionUser = (from prodUsers in productionQueue.GetProductionUsers()
                                  select new
                                  {
                                      prodUsers.UserID,
                                      Name = String.Format("{0} {1}", prodUsers.FirstName, prodUsers.LastName)

                                  });

            ViewBag.AssignedToUserId = new SelectList(productionUser, "UserID", "Name");

HUDHealthcarePortal/Views/Production/ProductionQueue/AppTaskAsignment.cshtml
@model Model.Production.ProductionTaskAssignmentModel
@{
    Layout = null;
}
<style type="text/css">
    .well {
        background: #d9edf7;
    }

</style>
<div class="modal-dialog" style="width: 400px;">
    <div class="modal-content">


        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 id="myModalLabel">Production Task Assignment</h4>
            <p id="message"></p>
        </div>

        @using (Html.BeginForm("UpdateApplicationTaskAsignment", "ProductionQueue", FormMethod.Post, new { @class = "modal-form", id = "myForm" }))
        {
            @Html.HiddenFor(m=>m.TaskId)
            @Html.HiddenFor(m=>m.TaskXrefid)
            @Html.HiddenFor(m=>m.TaskInstanceId)
            @Html.HiddenFor(m => m.PageTypeId)
           <div id="errorMsg" style="display: none" class="col-lg-offset-4">
             <h4 style="color: red;">Invalid Inputs</h4>
           </div>
            <div class="modal-body form-horizontal " style="height:150px;">
    <div class="row">

        @*<div class="form-group col-md-12">
            <label class="col-md-4 control-label">Task Name</label>
            <div class="col-md-8">
                @if (Model.TaskInstanceId == Guid.Empty)
                {
                    @Html.TextBoxFor(m => m.TaskXrefid, new {@class = "form-control", @readonly = true})
                }
                else
                {
                     @Html.TextBoxFor(m => m.TaskInstanceId, new {@class = "form-control", @readonly = true})
                }
               
            </div>
        </div>*@
    </div>
    <div class="row">
@if (Model.isWLM)
{
        <div class="form-group col-md-12">
            <label class="col-md-4 control-label">Assign To</label>
            <div class="col-md-8" >

                @Html.DropDownList("AssignedToUserId", null, new { @class = "form-control" })

            </div>
        </div>
}
       

    </div>

                <div class="row">

                    <div class="form-group col-md-12">
                        <label class="col-md-4 control-label">View</label>
                        <div class="col-md-8">

                            @Html.DropDownList("AssignedToViewId", null, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="col-md-offset-4">
                        <a id="assignToMe" href="#" style="color: #1e90ff !important; font-weight: bold; ">Assign To Me</a>
                    </div>

                </div>

               
            </div>

            <div class="modal-footer">
                <div class="col-sm-1 form-group pull-left">

                </div>
@if (Model.isWLM)
{
                <button class="btn btn-primary" type="submit">Assign</button>               
                <button class="btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
}

            </div>
        }
    </div>
    <!-- /.modal-content -->
</div>
<script type="text/javascript">
    function reloadGrid() {
        $("#ProductionQueue").trigger("reloadGrid");
        //$("#assignedTask").trigger("reloadGrid");
        Filter();
    }
    $("#myForm").submit(function (e) {

        e.preventDefault();
        var url = '@Url.Action("UpdateApplicationTaskAsignment", "ProductionQueue")';
        $.ajax({
            url: url,
            type: 'POST',
            data: $('#myForm').serialize(),
            success: function () {
                $('#sucess_alert').alert();
                $('#sucess_alert').fadeTo(1000, 500).slideUp(500, function () { $('#sucess_alert').slideUp(500) });
                reloadGrid();
                $('#dialogDiv').modal('toggle');
            },
            error: function (data) {
                alert("Error in Assigning User");
            },

        });

    });
    $("#assignToMe").click(function (e) {
        var url = '@Url.Action("SelfAssignApplicationTask", "ProductionQueue")';
        $.ajax({
            url: url,
            type: 'POST',
            data: $('#myForm').serialize(),
            success: function () {
                $('#sucess_alert').alert();
                $('#sucess_alert').fadeTo(1000, 500).slideUp(500, function() { $('#sucess_alert').slideUp(500) });
                //reloadGrid();
                $('#dialogDiv').modal('toggle');
                window.location.reload(true);
            },
            error: function (data) {
                //debugger;
                alert("Error in Assigning Workload Manager");
            },

        });
    });
</script>

HUDHealthcarePortal/Views/Production/ProductionQueue/Notes.cshtml
@using HUDHealthcarePortal.BusinessService
@model List<Model.Production.Prod_NoteModel>
@{
    ViewBag.Title = "Notes";
    Layout = null;
}
<style type="text/css">
    .modal-body {
        position: relative;
        overflow-y: auto;
        max-height: 400px;
    }   
    hr {
        margin-top: 20px;
        margin-bottom: 20px;
        border: 0;
        color: red;
        border-top: 2px solid #eee;
    }
</style>
<div class="modal-dialog" style="width: 500px;">
    <div class="modal-content">


        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">&times;</button>
            <h4 class="modal-title">Notes </h4>
        </div>
        <div class="modal-body" id="modalBody">          
            @foreach (var note in Model)
            {
                var ID = note.NoteId;
                <div class="AllComments" id='@note.NoteId'>
                    @if (note.NoteId != 0)
{
    <div>
        <p style="margin-bottom: 2px;">
            <a href="#" style="color: blue"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a> @note.CreatedByUserName
            On  <span style="color:green">@note.DateCreated</span>
        </p>
    </div>
                        <div class="col-lg-12">
                            <div class="col-lg-11  prodUser well" style="margin-top: 2px; background: lightblue">
                                <p class="text"> @note.Note</p>

                            </div>
                            @if (note.CreatedBy == UserPrincipal.Current.UserId)
                            {
                                <div class="col-lg-1" style="top: 26px; left: -3px">
                                    <a href="#" onclick='return removeComment(@note.NoteId)'>
                                        <span style="color:red;" class="glyphicon glyphicon-trash"></span>
                                    </a>
                                </div>
                            }

                        </div>
                    }
                </div>                  
            }
            <form role="form" id="noteForm">
                <div class="form-group">
                    <label for="comment">Comment:</label>
                    <textarea class="form-control" rows="5" id="comment"></textarea>
                </div>
                <div class="form-group">
                    <button class="btn btn-default">Add</button>
                </div>
            </form>           
        </div>

        <div class="modal-footer">

        </div>
    </div>
    
    <!-- /.modal-content -->
</div>

<script type="text/javascript">    
    $("#noteForm").submit(function (e) {
        var instanceId = '@Model.FirstOrDefault().TaskInstanceId';
        e.preventDefault();
        var commentText = $('#comment').val();
        if (commentText != '') {
            var url = '@Url.Action("AddNote", "ProductionQueue")';
            $.ajax({
                url: url,
                type: 'POST',
                data: { taskInstanceId: instanceId, notes: commentText },
                success: function (data) {                 
                    displayComment(data);
                },
                error: function (data) {
                    alert("Error on Adding Comment");
                },

            });
        }


    });

    function displayComment(noteId) {
        var dNow = new Date();
        var ampm = dNow.getHours() >= 12 ? 'PM' : 'AM';
        var currentDate = (dNow.getMonth() + 1) + '/' + dNow.getDate() + '/' + dNow.getFullYear() + ' ' + dNow.getHours() + ':' + dNow.getMinutes() + ':' + dNow.getSeconds() + ' ' + ampm;

        var comment = $('#comment').val();
        if (comment != '') {
            var userComment = '<div class="AllComments"  id=' + noteId + '>'
                               + '<p style="margin-bottom: 2px;">' +
                                '<a href="#" style="color: blue"><span class="glyphicon glyphicon-user" aria-hidden="true"></span></a>' + '@UserPrincipal.Current.UserName' + "      On  " + '<span style="color:green">' + currentDate + '</span>' + '</p>' +
          '<div class="col-lg-12">' +
         '<div class="col-lg-11  prodUser well" style="margin-top: 2px;background: lightblue">' +

        '<p class="text">' + comment + '</p>' +
        '</div>' +
        '<div class="col-lg-1" style="top: 26px; left: -3px">' +
                                    '<a href="#" onclick="return removeComment(' + noteId + ')"><span style="color:red;" class="glyphicon glyphicon-trash"></span>' +
                                    '</a>' +
                                '</div>' +
    '</div>'
            if ($('.AllComments:last').size() == 0) {
                $('#noteForm').prepend($(userComment));
                $('#comment').val('');
            }
            else {
                $('.AllComments:last').append($(userComment));
                $('#comment').val('');
            }
          
        }
    }

    function removeComment(id) {

        var url = '@Url.Action("Deletenote", "ProductionQueue")';
        $.ajax({
            url: url,
            type: 'POST',
            data: { noteId: id },
            success: function () {
                $('#' + id).remove();
            },
            error: function (data) {
                alert("Error on Deleting Comment");
            },

        });

    }
</script>

HUDHealthcarePortal/Views/Production/ProductionQueue/TaskAsignment.cshtml
@model Model.Production.ProductionTaskAssignmentModel
@{
    Layout = null;
}
<style type="text/css">
    .well {
        background: #d9edf7;
    }

</style>
<div class="modal-dialog" style="width: 400px;">
    <div class="modal-content">


        <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            <h4 id="myModalLabel">Production Task Assignment</h4>
            <p id="message"></p>
        </div>

        @using (Html.BeginForm("UpdateTaskAsignment", "ProductionQueue", FormMethod.Post, new { @class = "modal-form", id = "myForm" }))
    {
        @Html.HiddenFor(m => m.TaskId)
        @Html.HiddenFor(m => m.TaskXrefid)
        @Html.HiddenFor(m => m.TaskInstanceId)
        @Html.HiddenFor(m => m.PageTypeId)
        @Html.HiddenFor(m => m.Status)
        <div id="errorMsg" style="display: none" class="col-lg-offset-4">
            <h4 style="color: red;">Invalid Inputs</h4>
        </div>
        <div class="modal-body form-horizontal " style="height:150px;">
            <div class="row">

                <div class="form-group col-md-12">
                    <label class="col-md-4 control-label">Task</label>
                    <div class="col-md-8">

                        @Html.TextBoxFor(m => m.TaskName, new { @class = "form-control", @readonly = true })

                    </div>
                </div>
            </div>
            <div class="row">
                @if (Model.isWLM)
            {
                <div class="form-group col-md-12">
                    <label class="col-md-4 control-label">Assign To</label>
                    <div class="col-md-8">

                        @Html.DropDownList("AssignedToUserId", null, new { @class = "form-control" })

                    </div>
                </div>
        }
                <div class="col-md-offset-4">
                    <a id="assignToMe" href="#" style="color: #1e90ff !important; font-weight: bold; ">Assign To Me</a>
                </div>


            </div>

        </div>

        <div class="modal-footer">
            <div class="col-sm-1 form-group pull-left">

            </div>
            @if (Model.isWLM)
        {
            <button class="btn btn-primary" type="submit">Assign</button>
            <button class="btn-default" data-dismiss="modal" aria-hidden="true">Cancel</button>
    }
        </div>
}
    </div>
    <!-- /.modal-content -->
</div>
<script type="text/javascript">
    function reloadGrid() {
        $("#ProductionQueue").trigger("reloadGrid");
        Filter();
        //$("#assignedTask").trigger("reloadGrid");
    }
    $("#myForm").submit(function (e) {

        e.preventDefault();
        var url = '@Url.Action("UpdateTaskAsignment", "ProductionQueue")';
        $.ajax({
            url: url,
            type: 'POST',
            data: $('#myForm').serialize(),
            success: function () {
                $('#sucess_alert').alert();
                $('#sucess_alert').fadeTo(1000, 500).slideUp(500, function () { $('#sucess_alert').slideUp(500) });
                reloadGrid();
                $('#dialogDiv').modal('toggle');
            },
            error: function (data) {
                alert("Error in Assigning User");
            },

        });

    });
    $("#assignToMe").click(function (e) {
        
        var url = '@Url.Action("AssignToMe", "ProductionQueue")';
        $.ajax({
            url: url,
            type: 'POST',
            data: $('#myForm').serialize(),
            success: function () {
                
                $('#sucess_alert').alert();
                $('#sucess_alert').fadeTo(1000, 500).slideUp(500, function() { $('#sucess_alert').slideUp(500) });
                //reloadGrid();
                
                $('#dialogDiv').modal('toggle');
                window.location.reload(true);
            },
            error: function (data) {
                alert("Error in Assigning Workload Manager");
            }

        });
        
       
    });
</script>