HUDHealthcarePortal/Controllers/Production/AdhocController.cs
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.Core;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class AdhocController : Controller
    {
        //
        // GET: /Adhoc/

        public ActionResult Index()
        {
            var timeZoneInfo = TimeZoneInfo.FindSystemTimeZoneById(UserPrincipal.Current.Timezone);
            var reportDate = TimeZoneInfo.ConvertTimeFromUtc(DateTime.UtcNow, timeZoneInfo).ToString("MM/dd/yyyy hh:mm:ss tt");
            Session["ReportDate"] = timeZoneInfo.SupportsDaylightSavingTime ? reportDate + " " + TimezoneManager.ShortTimeZoneFormat(timeZoneInfo.DaylightName) 
                : reportDate + " " + TimezoneManager.ShortTimeZoneFormat(timeZoneInfo.StandardName);
            return View("~/Views/Production/Adhoc/Index.cshtml");
        }

    }
}

HUDHealthcarePortal/Controllers/Production/LenderProdTaskReassignmentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using System.Windows.Forms;
using BusinessService.Interfaces;
using Elmah;
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.BusinessService.Interfaces;
using HUDHealthcarePortal.BusinessService.ProjectAction;
using HUDHealthcarePortal.Core;
using HUDHealthcarePortal.Core.Utilities;
using HUDHealthcarePortal.Helpers;
using HUDHealthcarePortal.Model;
using HUDHealthcarePortal.Model.ProjectAction;
using BusinessService.ProjectAction;
using HUDHealthCarePortal.Helpers;
using Model.ProjectAction;
using MvcSiteMapProvider;
using MvcSiteMapProvider.Web.Mvc.Filters;
using WebGrease.Css.Extensions;
using BusinessService.AssetManagement;
using BusinessService;
using Model;
using Model.Production;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using BusinessService.Interfaces.Production;
using BusinessService.Production;
using BusinessService.ManagementReport;
using System.Configuration;
using System.Collections;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class LenderProdTaskReassignmentController : Controller
    {
        //
        private IProductionPAMReportManager _plmProdReportMgr;
        private ILenderProductionReassignReportManager _reassignReportMgr;
        private ITaskManager _taskManager;
        private IBackgroundJobMgr _backgroundJobManager;
        private IEmailManager _emailManager;
        private ITaskManager taskManager;
        private IAccountManager accountManager;
        public LenderProdTaskReassignmentController()
            : this(new ProductionPAMReportManager(), new TaskManager(), new LenderProductionReassignReportManager(), new BackgroundJobMgr(), new EmailManager(), new TaskManager(), new AccountManager())
        {

        }

        public LenderProdTaskReassignmentController(IProductionPAMReportManager PAMProdReportManager, ITaskManager taskManager, ILenderProductionReassignReportManager reassignReportMgr, IBackgroundJobMgr backgroundJobManager, IEmailManager emailManager, ITaskManager _taskManager, IAccountManager _accountManager)
        {
            _plmProdReportMgr = PAMProdReportManager;
            _taskManager = taskManager;
            _reassignReportMgr = reassignReportMgr;
            _backgroundJobManager = backgroundJobManager;
            _emailManager = emailManager;
            taskManager = _taskManager;
            accountManager = _accountManager;
        }



        public ActionResult Index(string prodUserIds = null, string fromDate = null, string toDate = null,
           string status = null, string projectAction = null, string isApplicationOrTaskLevel = null)
        {
            ViewBag.ExcelExportAction = "ExportProdPAMReport";

            ViewBag.GetProjectTypesByAppTypeAction = Url.Action("GetProjectTypesByAppType");
            ViewBag.SearchRequestsUrl = Url.Action("SearchForRequests");
            var viewModel = InitializeViewModel(prodUserIds, fromDate, toDate, status, projectAction,
                isApplicationOrTaskLevel);
            return View("~/Views/Production/ProductionTaskReassignment/LenderProdReassignmentReport.cshtml", viewModel);

        }

        public JsonResult GetProjectTypesByAppType(string value)
        {
            List<object> projectTypeObjs = new List<object>();
            var proejctTypes = _plmProdReportMgr.GetProjectTypesByAppType(value);
            projectTypeObjs = new List<object>(proejctTypes.Count);
            foreach (var m in proejctTypes)
            {
                projectTypeObjs.Add(new { Key = m.ProjectTypeId, Value = m.ProjectTypeName });
            }
            return Json(new { data = projectTypeObjs }, JsonRequestBehavior.AllowGet);
        }



        private LenderProductionReasignReportModel InitializeViewModel(string prodUserIds, string fromDate, string toDate,
            string status, string projectAction, string isApplicationOrTaskLevel)
        {
            var viewModel = new LenderProductionReasignReportModel(ReportType.ProdTaskReassignment);
            var userName = UserPrincipal.Current.UserName;
            string prodWLMName = string.Empty;

            var isDefaultSearch = false;
            var LenderUsers = _plmProdReportMgr.GetAllLenderUsers(UserPrincipal.Current.LenderId).ToList();
            ;

            if (RoleManager.IsUserLenderRole(userName) || RoleManager.IsUserLamBamLar(userName))
            {
                prodWLMName = UserPrincipal.Current.FullName;
            }

            var prodPageTypes = _plmProdReportMgr.GetProductionPageTypes();

            var prodProjectTypes = _plmProdReportMgr.GetProjectTypeModels();
            viewModel.LenderUser = new MultiSelectList(LenderUsers, "UserID", "Name");
            viewModel.ProductionPageTypes = new MultiSelectList(prodPageTypes, "PageTypeId", "PageTypeDescription");

            viewModel.ProductionProjecTypeList = new MultiSelectList(prodProjectTypes, "ProjectTypeId",
                "ProjectTypeName");

            return viewModel;
        }
        public JsonResult GetTReassignTasks(string sidx, string sord, int page, int rows, string appType, string programType, string lenderUserIds, DateTime? fromDate, DateTime? toDate, bool search = false)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            var currentUser = UserPrincipal.Current;
           
            var reassigntasks = new LenderProductionReasignReportModel(ReportType.ProdTaskReassignment);

            object jsonData = null;
            if (search)
            {
                reassigntasks = _reassignReportMgr.GetLenderProdReassignmentTasks(appType, programType, lenderUserIds,
fromDate == null ? (DateTime?)null : DateTime.Parse(fromDate.ToString()),
fromDate == null ? (DateTime?)null : DateTime.Parse(toDate.ToString()));

                if (reassigntasks != null)
                {
                    foreach (var item in reassigntasks.ReassignGridProductionlList)
                    {
                        //item.StartDate = TimezoneManager.ToMyTimeFromUtc(item.StartDate);
                        //item.EndDate = TimezoneManager.ToMyTimeFromUtc(item.EndDate);
                        item.StartDate = item.StartDate;
                        item.EndDate = item.EndDate;
                        item.ProcessedBy = accountManager.GetFullUserNameById(item.ProcessedById);
                    }

                    int totalrecods = reassigntasks.ReassignGridProductionlList.Count;
                    var totalpages = (int)Math.Ceiling((float)totalrecods / (float)rows);

                    var results = reassigntasks.ReassignGridProductionlList.Skip(pageIndex * pageSize).Take(pageSize);
                    var outresults = results.GroupBy(s => s.Groupid).SelectMany(gr => gr).ToList();
                    jsonData = new
                    {
                        total = totalpages,
                        page,
                        records = totalrecods,
                        rows = outresults.OrderBy(x=>x.FhaRequestType).ToList(),

                    };
                }


            }

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }




      

        [HttpPost]
        public void ReassignTasks(List<string> kvp, int AssignUserId, string AssignetoName, int FromProdUser, string AssigneFromName)
        {
            var AssignetoEmail = _plmProdReportMgr.GetUserInfoByID(AssignUserId);
            var AssigneFromEmail = _plmProdReportMgr.GetUserInfoByID(FromProdUser);
            _reassignReportMgr.LenderReassignTasks(kvp, AssignUserId);
            foreach (var item in kvp)
            {
                string[] pair = item.Split('|');

                bool Result = _backgroundJobManager.SendLenderProdTempTaskReassignmentEmail(_emailManager, AssigneFromEmail, AssigneFromName, AssignetoEmail, AssignetoName, pair[2], pair[3], pair[4], pair[5]);
            }

        }


      



    }
}

HUDHealthcarePortal/Controllers/Production/ProdTaskReassignmentController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity.Infrastructure;
using System.IO;
using System.Linq;
using System.Net.Configuration;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI;
using System.Windows.Forms;
using BusinessService.Interfaces;
using Elmah;
using HUDHealthcarePortal.BusinessService;
using HUDHealthcarePortal.BusinessService.Interfaces;
using HUDHealthcarePortal.BusinessService.ProjectAction;
using HUDHealthcarePortal.Core;
using HUDHealthcarePortal.Core.Utilities;
using HUDHealthcarePortal.Helpers;
using HUDHealthcarePortal.Model;
using HUDHealthcarePortal.Model.ProjectAction;
using BusinessService.ProjectAction;
using HUDHealthCarePortal.Helpers;
using Model.ProjectAction;
using MvcSiteMapProvider;
using MvcSiteMapProvider.Web.Mvc.Filters;
using WebGrease.Css.Extensions;
using BusinessService.AssetManagement;
using BusinessService;
using Model;
using Model.Production;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using BusinessService.Interfaces.Production;
using BusinessService.Production;
using BusinessService.ManagementReport;
using System.Configuration;
using System.Collections;

namespace HUDHealthcarePortal.Controllers.Production
{
    public class ProdTaskReassignmentController : Controller
    {
        //
        private IProductionPAMReportManager _plmProdReportMgr;
        private IProductionReassignReportManager _reassignReportMgr;
        private ITaskManager _taskManager;
        private IBackgroundJobMgr _backgroundJobManager;
        private IEmailManager _emailManager;
        private ITaskManager taskManager;
        public ProdTaskReassignmentController()
            : this(new ProductionPAMReportManager(), new TaskManager(), new ProductionReassignReportManager(), new BackgroundJobMgr(), new EmailManager(), new TaskManager())
        {

        }

        public ProdTaskReassignmentController(IProductionPAMReportManager PAMProdReportManager, ITaskManager taskManager, IProductionReassignReportManager reassignReportMgr, IBackgroundJobMgr backgroundJobManager, IEmailManager emailManager, ITaskManager _taskManager)
        {
            _plmProdReportMgr = PAMProdReportManager;
            _taskManager = taskManager;
            _reassignReportMgr = reassignReportMgr;
            _backgroundJobManager = backgroundJobManager;
            _emailManager = emailManager;
            taskManager = _taskManager;
        }

       

        public ActionResult Index(string prodUserIds = null, string fromDate = null, string toDate = null,
           string status = null, string projectAction = null, string isApplicationOrTaskLevel = null)
        {
            ViewBag.ExcelExportAction = "ExportProdPAMReport";
         
            ViewBag.GetProjectTypesByAppTypeAction = Url.Action("GetProjectTypesByAppType");
            ViewBag.SearchRequestsUrl = Url.Action("SearchForRequests");
            var viewModel = InitializeViewModel(prodUserIds, fromDate, toDate, status, projectAction,
                isApplicationOrTaskLevel);
            return View("~/Views/Production/ProductionTaskReassignment/ProdReassignmentReport.cshtml", viewModel);
           
        }

        public JsonResult GetProjectTypesByAppType(string value)
        {
            List<object> projectTypeObjs = new List<object>();
            var proejctTypes = _plmProdReportMgr.GetProjectTypesByAppType(value);
            projectTypeObjs = new List<object>(proejctTypes.Count);
            foreach (var m in proejctTypes)
            {
                projectTypeObjs.Add(new { Key = m.ProjectTypeId, Value = m.ProjectTypeName });
            }
            return Json(new { data = projectTypeObjs }, JsonRequestBehavior.AllowGet);
        }



        private ProductionReasignReportModel InitializeViewModel(string prodUserIds, string fromDate, string toDate,
            string status, string projectAction, string isApplicationOrTaskLevel)
        {            
            var viewModel = new ProductionReasignReportModel(ReportType.ProdTaskReassignment);
            var userName = UserPrincipal.Current.UserName;
            string prodWLMName = string.Empty;

            var isDefaultSearch = false;
            var prodUsers = _plmProdReportMgr.GetProductionUsers().ToList();
            ;

            if (RoleManager.IsProductionWLM(userName))
            {
                prodWLMName = UserPrincipal.Current.FullName;
            }

            var prodPageTypes = _plmProdReportMgr.GetProductionPageTypes();
           
            var prodProjectTypes = _plmProdReportMgr.GetProjectTypeModels();
            viewModel.ProductionUsers = new MultiSelectList(prodUsers, "UserID", "Name");
            viewModel.ProductionPageTypes = new MultiSelectList(prodPageTypes, "PageTypeId", "PageTypeDescription");
         
            viewModel.ProductionProjecTypeList = new MultiSelectList(prodProjectTypes, "ProjectTypeId",
                "ProjectTypeName");

            return viewModel;
        }

        public JsonResult GetTReassignTasks(string sidx, string sord, int page, int rows, string appType, string programType, string prodUserIds, DateTime? fromDate, DateTime? toDate,bool search=false)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            var currentUser = UserPrincipal.Current;
            //format date
            //DateTime? fromUTCDate = null;
            // DateTime? toUTCDate = null;
            //if(fromDate!=null)
            //{
            //    fromUTCDate =  TimezoneManager.GetUtcTimeFromPreferred(Convert.ToDateTime(fromDate));
            //}

            //if (toDate != null)
            //{
            //   toUTCDate = TimezoneManager.GetUtcTimeFromPreferred(Convert.ToDateTime(toDate));
            //}
            var reassigntasks = new ProductionReasignReportModel(ReportType.ProdTaskReassignment);

            object jsonData=null;
            if (search)
            {
                reassigntasks = _reassignReportMgr.GetProdReassignmentTasks(appType, programType, prodUserIds,
fromDate == null ? (DateTime?)null : DateTime.Parse(fromDate.ToString()),
fromDate == null ? (DateTime?)null : DateTime.Parse(toDate.ToString()));

                if (reassigntasks != null)
                {
                    foreach (var item in reassigntasks.ReassignGridProductionlList)
                    {
                        //item.StartDate = TimezoneManager.ToMyTimeFromUtc(item.StartDate);
                        //item.EndDate = TimezoneManager.ToMyTimeFromUtc(item.EndDate);
                        item.StartDate = item.StartDate;
                        item.EndDate = item.EndDate;
                    }



                    int totalrecods = reassigntasks.ReassignGridProductionlList.Count;
                    var totalpages = (int)Math.Ceiling((float)totalrecods / (float)rows);









                    var results = reassigntasks.ReassignGridProductionlList.Skip(pageIndex * pageSize).Take(pageSize);
                    var outresults = results.GroupBy(s => s.Groupid).SelectMany(gr => gr).ToList();
                    jsonData = new
                    {
                        total = totalpages,
                        page,
                        records = totalrecods,
                        rows = outresults,

                    };
                }


            }
            
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public void ReassignTasks(List<string> kvp, int AssignUserId,string AssignetoName, int FromProdUser, string AssigneFromName)
        {
            var AssignetoEmail = _plmProdReportMgr. GetUserInfoByID(AssignUserId);
            var AssigneFromEmail = _plmProdReportMgr.GetUserInfoByID(FromProdUser);
            _reassignReportMgr.ReassignTasks(kvp, AssignUserId);
            foreach (var item in kvp)
            {
                string[] pair = item.Split('|');
                
               bool Result= _backgroundJobManager.SendProdTempTaskReassignmentEmail(_emailManager, AssigneFromEmail, AssigneFromName, AssignetoEmail, AssignetoName, pair[2],pair[3], pair[4], pair[5]);
            }
            
        }



    }
}

HUDHealthcarePortal/Views/Production/ProductionTaskReassignment/LenderProdReassignmentReport.cshtml
@using Core
@using HUDHealthcarePortal.BusinessService
@model Model.Production.LenderProductionReasignReportModel
@{
    ViewBag.Title = "Lender ProdReassignment Report";
}


<style type="text/css">
    .overlay {
        position: fixed;
        background-color: #FAFAFA;
        z-index: 2147483647 !important;
        opacity: 0.8;
        overflow: hidden;
        text-align: center;
        bottom: 0;
        right: 0;
        left: 0;
        top: 0;
        height: 100%;
        width: 100%;
    }
</style>
<style>
    ol {
        margin-left: -40px;
    }

        ol il {
            float: left;
            width: 290px;
        }

    br {
        clear: left;
    }

    div.wrapper {
        margin-bottom: 20px;
    }

    .datePickerTextBox {
        width: 100px;
        height: 25px;
    }

    .highrisk {
        color: black;
        padding-top: 6px;
        padding-bottom: 6px;
        padding-left: 5px;
        margin-left: -4px;
        padding-right: 6px;
        margin-right: -5px;
    }

    tr.header_row th:nth-child(5) {
        width: auto;
    }

    tr.item_row td:nth-child(5) {
        width: auto;
    }

    .ui-multiselect {
        padding: 2px 0 2px 4px;
        text-align: left;
        border: 1px solid black;
    }

    .ui-multiselect {
        font-size: 12px;
    }

    .multiselect option {
        display: block;
        font-size: 8px !important;
    }

    /* remove label borders in IE6 because IE6 does not support transparency */

    * html .ui-multiselect-checkboxes label {
        border: none;
        padding: 10px;
    }

    tr.header_row th:nth-child(5) {
        width: 300px;
    }
</style>

<!-- Add all Page Specific CSS files here -->
<!-------------------------------------------------------------------------------------------------------------------------- -->
<link href="~/Scripts/jquery-multiSelect/jquery.multiselect.css" rel="stylesheet" type="text/css" />
<script src="~/Scripts/jquery-ui-1.10.4.min.js"></script>
<!-------------------------------------------------------------------------------------------------------------------------- -->
@using (Html.BeginForm())
{



    <div class="row " style="padding: 5px;">

        @Html.Partial("~/Views/Production/ProductionTaskReassignment/_LenderCommonSearchReassignment.cshtml", Model)

    </div>



    <div>
        <div id="dvUserReport">
            @Html.Partial("~/Views/Production/ProductionTaskReassignment/_LenderReassignSearchResult.cshtml", Model)
        </div>
    </div>



    <div class="container-fluid">
        <div class="row" style="padding: 5px;">


        </div>
    </div>
    <div id="divassign" class="container-fluid">
        <div class="row" style="padding: 5px;">
            <span class="col-md-4 text-left">
                @Html.Label("Assign To: ")
            </span>
            <span class="col-md-4 text-left">

                @*@Html.DropDownList("assignProdUserlst", Model.ProductionUsers, new { name = "assignProdUserlst" })*@
                @Html.DropDownListFor(m => m.LenderUser, Model.LenderUser, "Select Lender User", new { id = "assignProdUserlst" })
            </span>
        </div>
    </div>

    <div id="divreassign" class="container-fluid">
        <div class="row" style="padding: 5px;">
            <span class="col-md-4 text-left">
                <input id="btnreassign" type="button" class="form-control" value="ReAssign">
            </span>

        </div>
    </div>



}
<script>


    $(document).ready(function () {


        $('#btnreassign').click(function (element) {

            var rowidlist;
            var list = [];
            rowidlist = $("#LenderReassignGrid").jqGrid('getGridParam', 'selarrrow');
            var InstanceID;
			var FhaRequestType;
			var AssignUserId;
			var FromProdUser;
            //debugger;
            if (rowidlist.length == "") {
                alert('Please select a Task to continue');
                return false;
            }
            if ($('#assignProdUserlst').val() == "" ) {
                alert('Please select a User to Assign Task');
                return false;
            }



            //code for passing Taskinstanceid and User id's
            //debugger;
            //var id = $('#lstProdUser').val();

            for (var i in rowidlist) {
                //alert(rowidlist[i]);

                InstanceID = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'ParentChildInstanceId');
                FhaRequestType = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'FhaRequestType');
                FhaNumber = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'fhanumber');
                PropertyName = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'ProjectName');
                ProductionTaskType = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'ProductionTaskType');
                viewname = $("#LenderReassignGrid").jqGrid('getCell', rowidlist[i], 'TaskName');
				AssignUserId = $('#assignProdUserlst').val();
				FromProdUser = $('#lstProdUser').val();
				list.push(InstanceID + "|" + FhaRequestType + "|" + FhaNumber + "|" + PropertyName + "|" + ProductionTaskType + "|" + viewname + "|" + AssignUserId + "|" + FromProdUser);
            }
            //alert(list.join(", "));
           //debugger;
            $.ajax({
                url: '@Url.Action("ReassignTasks", "LenderProdTaskReassignment")',
                data: JSON.stringify({
                    kvp: list,
                    AssignUserId: $('#assignProdUserlst').val(),
                    AssignetoName: $('#assignProdUserlst :selected').text(),
                    FromProdUser: $('#lstProdUser').val(),
                    AssigneFromName: $('#lstProdUser :selected').text()

                }),
                cache: false,
                type: 'POST',
                contentType: "application/json",
                success: function (response) {
                    //  debugger;
                    $("#LenderReassignGrid").trigger("reloadGrid");
                    @*jQuery("#ReassignGrid").jqGrid().setGridParam({
                        url: '@Url.Action("GetTReassignTasks", "ProdTaskReassignment")', datatype: 'json', postData:
                                { appType: pageTypeIds, programType: programTypeIds, prodUserIds: prodUserIds, fromDate: _minUploadDate, toDate: _maxUploadDate, search: true }
                    }).trigger("reloadGrid");*@
                 alert('Tasks Reassigned Successfully')

                },
                error: function (xhr) {
                   // debugger;
                    alert('Tasks Reassign Failed')
                }
            });

        });


    });
</script>