HUDHealthcarePortal/Controllers/HelpDesk/Default2Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HUDHealthcarePortal.Controllers.HelpDesk
{
    public class GetDemoController : ApiController
    {
        // GET api/default2        
        public HttpResponseMessage Get()
        {
            return Request.CreateResponse(HttpStatusCode.OK, new string[] { "Hello", "World" });
        }

    }
}

HUDHealthcarePortal/Controllers/HelpDesk/Default3Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HUDHealthcarePortal.Controllers.HelpDesk
{
    public class abcClass
    {
        public string Name { get; set; }
        public string SirName { get; set; }
    }

    public class UpdateDemoController : ApiController
    {
        public HttpResponseMessage Get(int id, [FromBody] abcClass value)
        {
            return Request.CreateResponse(HttpStatusCode.OK, value);
        }
    }
}

HUDHealthcarePortal/Controllers/HelpDesk/Default4Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HUDHealthcarePortal.Controllers.HelpDesk
{
    public class PostDemoController : ApiController
    {
        public HttpResponseMessage Get([FromBody] abcClass value)
        {
            return Request.CreateResponse(HttpStatusCode.OK, "Thanks, received your data");
        }
    }
}

HUDHealthcarePortal/Controllers/HelpDesk/Default6Controller.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace HUDHealthcarePortal.Controllers.HelpDesk
{
    public class TestDemo1Controller : ApiController
    {
        // GET api/default6
        public IEnumerable<string> Get()
        {
            return new string[] { "value1", "value2" };
        }

        // GET api/default6/5
        public string Get(int id)
        {
            return "value";
        }

        // POST api/default6
        public HttpResponseMessage Post([FromBody] abcClass value)
        {
            return Request.CreateResponse(HttpStatusCode.OK, value);
        }

        // PUT api/default6/5
        public HttpResponseMessage Put(int id, [FromBody] abcClass value)
        {
            return Request.CreateResponse(HttpStatusCode.OK, value);
        }

        // DELETE api/default6/5
        public void Delete(int id)
        {
        }
    }
}

HUDHealthcarePortal/Controllers/HelpDesk/HelpDeskController.cs
using System;
using System.Web.Mvc;
using HUDHealthcarePortal.Model;
using HUDHealthcarePortal.Core;
using HelpDeskController.Repository;
using System.Collections.Generic;
using HUDHealthcarePortal.BusinessService;
using System.IO;
using System.Web;
using HUDHealthCarePortal.Filters;
using HUDHealthcarePortal.Filters;
using BusinessService.Interfaces;
using System.Collections;
using Repository.Interfaces;
using System.Data;
using System.Text;
using System.Configuration;
using EntityObject.Entities.HCP_live;
using System.Threading.Tasks;
using BusinessService.AssetManagement;
using BusinessService.ProjectAction;
using System.Linq;
using HUDHealthcarePortal.Helpers;
using SpreadsheetGear;
using EntityObject.Entities.HCP_live.Programmability;


//karri:#149,#214
//https://www.c-sharpcorner.com/article/upload-files-in-asp-net-mvc-5/
//https://docs.microsoft.com/en-us/aspnet/core/razor-pages/upload-files?view=aspnetcore-2.2
//https://www.c-sharpcorner.com/article/asp-net-mvc-form-with-file-upload/

namespace HelpDeskController
{
    public class HelpDeskController : Controller
    {
        // private HUDHealthcarePortal.Repository.UnitOfWork _unitOfWork;
        //private IAdminManagerUsersRepository _adminManagerUsersRepository;
        ArrayList _sameGroupUsers = new ArrayList();
        IBackgroundJobMgr _backgroundManager = null;
        private IReserveForReplacementManager reserveForReplacementManager;
        private IProjectActionFormManager projectActionFormManager;
        private IUploadDataManager uploadDataManager;
        IEmailManager _emailManager = null;
        IAccountManager _accountManager = null;
        //controller constructor is called every time a action is initiated
        HDTicketManager _hdtktmngr = null;
        HDTicketLoggerMngr _hdtktnotifmngr = null;//HDNOTIFICAITONS

        Hashtable _htLoggedUserRole = null;
        int _userid;
        //ArrayList _hudHelpDeskUsers = new ArrayList();
        List<SelectListItem> _hdAdminUsersList = new List<SelectListItem>();
        //written by siddesh 28082019   #344//
        IUploadDataManager _uploadDataMgr = null;

        public HelpDeskController()
        {
            //_unitOfWork = new HUDHealthcarePortal.Repository.UnitOfWork(DBSource.Live);
            //_adminManagerUsersRepository = new HUDHealthcarePortal.Repository.AdminManagerUsersRepository(_unitOfWork);
            //NOTE:we cannot use Server.MapPath("~/UploadedHelpDeskTktFiles/") since we are still in Constructor itself 
            _hdtktmngr = new HDTicketManager(ConfigurationManager.AppSettings["HUDHelpDeskMetaFile"].ToString());
            _hdtktnotifmngr = new HDTicketLoggerMngr();//HDNOTIFICAITONS

            _userid = UserPrincipal.Current.UserId;
            uploadDataManager = new UploadDataManager();
            projectActionFormManager = new ProjectActionFormManager();

            _accountManager = new AccountManager();
            _backgroundManager = new BackgroundJobMgr();
            _emailManager = new EmailManager();
            reserveForReplacementManager = new ReserveForReplacementManager();
            //written by siddesh 28082019   #344//
            _uploadDataMgr = new UploadDataManager();
            _htLoggedUserRole = new Hashtable();
            _htLoggedUserRole["TechDesk"] = false;
            _htLoggedUserRole["HUDAdmin"] = false;
            _htLoggedUserRole["OtherUser"] = false;

            //setting of the role from the logged user
            foreach (var role in UserPrincipal.Current.Roles)
            {
                //will be setting only for Admin and HD user
                if (_htLoggedUserRole.ContainsKey(role))
                {
                    _htLoggedUserRole[role] = true;
                }
            }
            //if all the values are false, then make true for OtherUser key
            bool isAKeyFound = false;
            foreach (DictionaryEntry entry in _htLoggedUserRole)
            {
                if (Convert.ToBoolean(entry.Value))
                {
                    isAKeyFound = true;
                    break;
                }
            }
            if (!isAKeyFound)
                _htLoggedUserRole["OtherUser"] = true;

            //string 1username = _accountManager.GetFullUserNameById(3318);
        }

        //doing nothing
        public ActionResult Index()
        {
            return View();
        }

        //opens create ticket form for "other than" "HDADMIN, HelpDesk" users only
        //CreateTicket.cshtml
        //SuperUser,Administrator,HUDAdmin,HUDDirector,WorkflowManager,LenderAdmin,LenderAccountManager,BackupAccountManager,AccountExecutive,LenderAccountRepresentative,InternalSpecialOptionUser,HUDAdmin,HelpDesk
        [HttpGet]
        [AccessDeniedAuthorize(Roles = "HUDAdmin,HUDDirector,LenderAdmin,LenderAccountManager,BackupAccountManager,LenderAccountRepresentative,AccountExecutive,WorkflowManager,Attorney,InternalSpecialOptionUser,ProductionUser,ProductionWlm,Reviewer")]
        public ActionResult CreateTicket()
        {
            //while creating a new ticket filling default values
            var hdt = new HD_TICKET_ViewModel();
            PopulatehelpdeskFHANumberList(hdt);
            DataTable dtStatus = _hdtktmngr.getStatusTbl();
            DataTable dtCategory = _hdtktmngr.getCateogryTbl();
            DataTable dtSubCategory = _hdtktmngr.getSubCategoryTbl();
            DataTable dtOnAction = _hdtktmngr.getOnActionTbl();

            foreach (DataRow dr in dtStatus.Rows)
                hdt.TicketStatusList.Add(new SelectListItem() { Text = dr["Text"].ToString(), Value = dr["Value"].ToString() });

            foreach (DataRow dr in dtCategory.Rows)
                hdt.TicketCategoryList.Add(new SelectListItem() { Text = dr["Text"].ToString(), Value = dr["Value"].ToString() });

            foreach (DataRow dr in dtSubCategory.Rows)
                hdt.TicketSubCategoryList.Add(new SelectListItem() { Text = dr["Text"].ToString(), Value = dr["Value"].ToString() });

            foreach (DataRow dr in dtOnAction.Rows)
                hdt.TicketOnActionList.Add(new SelectListItem() { Text = dr["Text"].ToString(), Value = dr["Value"].ToString() });


            //karrinew
            //display the created users firstname,last name, (user email)

            //these values do not persist as constructor is initiated afresh for every action,hence better in
            //submit function
            //hdt.LAST_MODIFIED_ON = DateTime.Now;
            hdt.LAST_MODIFIED_ON = DateTime.UtcNow;
            hdt.CREATED_BY_USERDISPLAYNAME = UserPrincipal.Current.FullName + "(" + UserPrincipal.Current.UserName + ")";//EMAIL ID
            hdt.CREATED_BY = UserPrincipal.Current.UserId;//userid in number
                                                          //hdt.CREATED_ON = DateTime.Now;
            hdt.CREATED_ON = DateTime.UtcNow;

            //we first create a folder on UserID_RandomNumber, fill in files into it, later Rename folder afer creating ticket
            Random randoms = new Random();
            var UniqueId = randoms.Next(0, 99999);

            //temperory folder will be userid\tempnumber in the folder "UploadedHelpDeskTktFiles"
            string newPath1 = UserPrincipal.Current.UserId + "_" + UniqueId;
            string newPath2 = Server.MapPath("~/UploadedHelpDeskTktFiles/" + newPath1);
            hdt.HELPDESK_UPLOADS_PATH = newPath2;

            hdt.TEMPERORY_FILE_UNIQUEPATH = UniqueId;

            return View(hdt);

        }

        //submission/saving data from CreateTicket.cshtml
        [HttpPost]
        public ActionResult SubmitForm(HD_TICKET_ViewModel hdt)
        {
            //Implemented by siddesh 01102019 Start//
            if (hdt.TICKET_ID > 0)
            {
                var hdticketsGridData = _hdtktmngr.GetMyTickets(0, hdt.TICKET_ID);
                if (hdticketsGridData.First().CONVERSATION != null && hdticketsGridData.First().CONVERSATION != "")
                    hdt.CONVERSATION = hdticketsGridData.First().CONVERSATION;

            }

            //Implemented by siddesh 01102019 End//
            string s2newPath = string.Empty;
            string newpath1 = string.Empty;
            int filescount = 0;
            int ticketid = 0;
            bool isUPDATE = false;

            bool isAdminUser = false;//Note: there is no HUDAdmin functionality, HUDAdmin now will become as HelpDesk1 role
            bool isHelpDesk1 = false;
            bool isOhterUser = false;
            bool isHelpDesk2 = false;
            bool isOnlyCmntsSubmitted = false;//karri-hareesh-13092019//to send mail if only comments are submitted

            int loggedUserID = 0;//userid = 0;
            IdentifyUserRole(ref isAdminUser, ref isHelpDesk1, ref isOhterUser, ref isHelpDesk2, UserPrincipal.Current.UserId);
            //if (isAdminUser || isHelpDesk1 || isHelpDesk2)
            if (isHelpDesk1 || isHelpDesk2)
                loggedUserID = 0;
            else
                loggedUserID = UserPrincipal.Current.UserId;

            if (hdt != null && ModelState.IsValid)
            {
                try
                {
                    //Note: Identify if NEW-CREATE or UPDATE
                    //if (isHelpDesk1 || isHelpDesk2 || isAdminUser)
                    //if (isHelpDesk1 || isHelpDesk2 || (isOhterUser && hdt.TICKET_ID > 0))
                    if ((isHelpDesk1 && hdt.TICKET_ID > 0) || (isHelpDesk2 && hdt.TICKET_ID > 0) || (isOhterUser && hdt.TICKET_ID > 0))
                        isUPDATE = true;

                    //hepful for UPDATE only
                    bool isStatusChanged = false;
                    bool isAssigned = false;
                    bool isReassigned = false;
                    bool isPriorityChanged = false;
                    bool isDataChanged = false;

                    #region CREATE
                    if (!isUPDATE)//if create
                    {

HUDHealthcarePortal/Views/HelpDesk/GetHelpDeskReports.cshtml
@model HD_TICKET_ViewModel
@*//karri:#149*@
@{
    ViewBag.Title = "Help Desk Reports";
    //Layout = "~/Views/Shared/_Layout.cshtml";
}
<link href="~/Content/ui.jqgrid.css" rel="stylesheet" />
<script src="~/Scripts/free-jqGrid/jquery.jqGrid.min.js"></script>
<link href="~/Content/themes/redmond/jquery-ui-1.12.1.custom/jquery-ui.css" rel="stylesheet" />
<script type="text/javascript" src="~/Content/themes/redmond/jquery-ui-1.12.1.custom/jquery-ui.js"></script>
<script type="text/javascript" src="~/Scripts/jquery-multiSelect/jquery.multiselect.js"></script>



@*<style>
        .modal-content{
            width:1300px;
            height:470px;
            position:center;
             left: 0px;
            top: 0px;
              right: 0px;

        }
        .modal-dialog{
           display:block;
           height:100%;
           width:100%;
           position:center;
           top:0;
           bottom:0;
           left:0;
           right:0;


        }

        #modalbody {
            position: center;
            left: 0px;
            top: 0px;
            width: 300%;
            height: 150%;
            right: 0px;
        }

    </style>*@
<style>
    #modalbody {
        position: center;
        left: 0px;
        top: 0px;
        width: 300%;
        height: 150%;
        right: 0px;
    }

    #modelContent {
        position: center;
        left: 0px;
        top: 0px;
        width: 150%;
        height: 150%;
        right: 0px;
    }

    #btnproceed {
        text-align: center;
        width: 100%;
        color: white;
    }

    .close {
        color: #0C1D7D;
    }

    .modal-dialog {
        display: block;
        height: 60%;
        width: 55%;
        position: center;
    }

    .modal-header {
        color: #0C1D7D;
    }

    h4 {
        color: #0C1D7D;
        font-size: large;
    }
    input{
        text-align: center;
    }
</style>
<h5>SEARCH By Options:</h5>
@using (Html.BeginForm("SearchHelpDeskTicket", "HelpDesk", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div class="container" style="width:1259px; border:groove;">
        <div class="row">
            <div class="col-sm-2" style="margin-right: -109px;margin-top: 25px;">
                <label>Status type </label>
            </div>
            <span class="col-md-3 text-left" style="margin-top:24px;margin-left:-2px">
                @Html.ListBox("lstIssue", Model.TicketStatusList, new { multiple = "multiple", name = "lstIssue",@style= "width:212px" })
            </span>
            @*Siddesh*@
           
            <div class="col-sm-2" style="margin-left: 44px;margin-top: 25px;">

                <label>HelpDesk Name </label>
            </div>
            @*Siddesh 11/10/2019 (added default select value)*@
            <div class="col-sm-2" >
                <div class="input-group" style="margin-left:-111px;">
                    @Html.DropDownListFor(model => model.ASSIGNED_TO_USERNAME, Model.TicketHelpdesknameList, "Select HelpDesk Name", new
               {
                   @id = "HelpDeskName",
                   @style = "width: 222px; margin-top:26px;margin-left:43px;"
               })
                </div>
            </div>
            </div>
            <div class="row">
                <div class="col-md-2  " style="margin-left: 14px;margin-top: 25px; ">

                    @Html.Label("Date From", new { @class = "required" ,@style= "margin-left: -12px;" })
                </div>
                <div class="col-md-2" style="margin-left:-127px;margin-top: 20px;">
                    @*@Html.TextBoxFor(m => m.REPORT_START_DATE, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker", id = "FromDate" })*@
                    @Html.TextBoxFor(m => m.REPORT_START_DATE, "{0:MM/dd/yyyy}" , new { placeHolder = "MM/DD/YYYY",@style= "width: 255px;", @class = "form-control datepicker", id = "FromDate" })
                </div>
                <div class="col-md-2 " style="margin-left: 87px;margin-top: 25px;">
                    @Html.Label("Date To", new { @class = "required" ,@style = "margin-left:65px;" })
                </div>
                <div class="col-md-2" style="margin-left:-3px;margin-top: 20px;width: 252px;">
                    @*@Html.TextBoxFor(m => m.REPORT_START_DATE, "{0:MM/dd/yyyy}", new { @class = "form-control datepicker", id = "FromDate" })*@
                    @Html.TextBoxFor(m => m.REPORT_END_DATE, "{0:MM/dd/yyyy}", new { placeHolder = "MM/DD/YYYY", @class = "form-control datepicker", id = "ToDate" })
                </div>
            </div>
        <div class="col-sm-2" style="margin-left:866px; margin-top: -37px;">
            <div class="input-group">
                <span class="button">
                    <input type="button" class="btn btn-default" value="Search" onclick="HelpDeskReportsFilterResults()" />
                </span>
                <span class="button">
                    <input type="button" class="btn btn-default" value="Reset" onclick="HelpDeskReportsResetFilterResults()" />
                </span>
            </div>
        </div>
        @*<span class="col-md-10">
                <i>
                    Click <a href="/HelpDesk/HelpDesk_Upload_Template" style="text-decoration:underline;">here</a>
                    to download the Help Desk Reports.
                </i>
            </span>*@
        @*written by siddesh 28082019   #344 *@
        <div class="row" style="margin-left:20px;width: 1200px;">
            <span style="float: right; margin-left: 80px">
                <a id="ExclIcon" class="excelExport" href="@Url.Action("ExportUploadStatusHelpdeskreports", "HelpDesk")"><img alt="Export to Excel" src="/Images/icon_excelBg.jpg"></a>

            </span>

        </div>
    </div>
}
<div>
    <table id="HelpDeskReportGrid"></table>
    <div id="jqGridPager"></div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#FromDate').val('');
        $('#ToDate').val('');
        $("#HelpDeskReportGrid").jqGrid({
            url: "/HelpDesk/GetHelpdeskReportsView",
                datatype: "json",
                colNames: ['TICKET ID', 'Number Of Days', 'Number Of Weeks', 'Status', 'FromDate', 'ToDate', 'HELP DESK NAME'],
                colModel: [
                { Key: false, name: 'TICKET_ID', index: 'TICKET_ID', editable: false},
            { Key: false, name: 'Numberofdays', index: 'Numberofdays', editable: false },
           { Key: false, name: 'Numberofweeks', index: 'Numberofweeks', editable: false},
          { Key: false, name: 'STATUS', index: 'Status', editable: false, },
           { Key: false, name: 'CREATED_ON', index: 'CREATED_ON', editable: false, formatter: 'date', formatoptions: { newformat: 'm/d/Y h:i A' } },
             { Key: false, name: 'LAST_MODIFIED_ON', index: 'LAST_MODIFIED_ON', editable: false, formatter: 'date', formatoptions: { newformat: 'm/d/Y h:i A' } },
                   { Key: false, name: 'Helpdesk_name', index: 'Helpdesk_name', editable: false },
                ],
                height:'100%',
                rowNum: 40,
                rowList: [40, 80, 120, 160, ],
                rownumbers: true,
                viewrecords: true,
                autowidth: true,
                autoencode: true,
                loadonce: true,
                sortable: true,
                sortable: 'STATUS',
                pager: true,
                pager: "#jqGridPager",
                caption: 'HelpDesk Reports',
                emptyrecords: 'No records to display',
                loadComplete: function () {
                    var $self = $(this);
                    if ($self.jqGrid("getGridParam", "datatype") === "json") {
                        setTimeout(function () {
                            $self.trigger("reloadGrid"); // Call to fix client-side sorting
                        }, 50);
                    }
                }
            });
        jQuery("#HelpDeskReportGrid").jqGrid('navGrid', '#pager', { edit: false, add: false, del: false, search: false });
         
        //$("LenderGroupTaskGrid").jqGrid('navGrid')
        // implemented by siddesh
                $("#lstIssue").multiselect({
                    noneSelectedText: 'Select Status', minWidth: 250
                                , selectedList: null
                                , selectedText: function (numChecked, numTotal) {
                                    var valSelected = $("#lstIssue").val();

                                    var aeSelected = numChecked == numTotal ? 'All' : numChecked;
                                    return 'Status (' + aeSelected + ')';
                                    //numChecked + ' of ' + numTotal + ' Request types selected';
                                }
                });
            });

            function getKPIParameters() {

            }

            // Implemented by hareesh
            function HelpDeskReportsFilterResults() {
                // Implemented by Siddesh
                var listBoxToString = function (listBox, all) {
                    if (typeof listBox === "string") {
                        listBox = document.getElementById(listBox);
                    }

                    if (listBox == null) { return ""; }

                    if (!(listBox || listBox.options)) {
                        throw Error("No options");
                    }
                    var options = [], opt;
                    for (var i = 0, l = listBox.options.length; i < l; ++i) {
                        opt = listBox.options[i];
                        if (all || opt.selected) {
                            options.push(opt.value);
                        }
                    }
                    return options.join(",");
                };
               var statuscheckbox = listBoxToString('lstIssue', false);
                $("#HelpDeskReportGrid").jqGrid('setGridParam', {
                    url: '@Url.Action("GetHelpdeskReportsViews", "HelpDesk")',
                    datatype: 'json',
                    postData: { "Status": statuscheckbox, "categorytype": $('#categorytype').val(), "FromDate": $('#FromDate').val(), "ToDate": $('#ToDate').val(), "HelpDeskName": $('#HelpDeskName').val() }
                   // postData: { "Status":  $('#issuetype').val(), "categorytype": $('#categorytype').val(), "FromDate": $('#FromDate').val(), "ToDate": $('#ToDate').val() }
                }).trigger('reloadGrid');
              $("#lstIssue").multiselect("refresh");

            }
    //written by siddesh  19092019 #365
    function ExportUploadStatusHelpdeskreports() {

        // Implemented by Siddesh
        var listBoxToString = function (listBox, all) {
            if (typeof listBox === "string") {
                listBox = document.getElementById(listBox);
            }
            if (listBox == null) { return ""; }
            if (!(listBox || listBox.options)) {
                throw Error("No options");
            }
            var options = [], opt;
            for (var i = 0, l = listBox.options.length; i < l; ++i) {
                opt = listBox.options[i];
                if (all || opt.selected) {
                    options.push(opt.value);
                }
            }
            return options.join(",");
        };
        var statuscheckbox = listBoxToString('lstIssue', false);

        //var datapost = { "Status": $("#issuetype option:selected").text(), "categorytype": $('#categorytype').val(), "FromDate": $('#FromDate').val(), "ToDate": $('#ToDate').val() };
        var datapost = "Status=" + statuscheckbox + "&FromDate=" + $('#FromDate').val() + "&ToDate=" + $('#ToDate').val();
        return "/HelpDesk/ExportUploadStatusHelpdeskreports/?"+ datapost;
        //$.ajax({
        //    url:"/HelpDesk/ExportUploadStatusHelpdeskreports",
        //    data: datapost,
        //    dataType: 'json',
        //    async: false,
        //    type: 'POST',
        //    success: function (response) {
        //        alert('s');
        //    },
        //    error: function (error) {
        //        //alert(error);
        //    }
        //});

    }
            // Implemented by hareesh
    function HelpDeskReportsResetFilterResults() {

        $('.ui-multiselect-none').click();
                $('#FromDate').val('');
                $('#ToDate').val('');
                var dropDown = document.getElementById("HelpDeskName");
                dropDown.selectedIndex = 0;
                // $('#lstIssue').val();
               // $("#lstIssue option").remove();
                $("#HelpDeskReportGrid").jqGrid('setGridParam', {
                    url: '@Url.Action("GetHelpdeskReportsViews", "HelpDesk")',
                    datatype: 'json',
                    postData: { "Status": '', "FromDate": $('#FromDate').val(), "ToDate": $('#ToDate').val(), "HelpDeskName": $('#HelpDeskName').val() }
                }).trigger('reloadGrid');
            }
</script>

<script>
            $(document).ready(function () {
                //alert(@ViewData["ReportStartDate"]);
                $('#FromDate').datepicker();
                $('#ToDate').datepicker();
            });
</script>

HUDHealthcarePortal/Views/HelpDesk/_HDFilter.cshtml
@model HUDHealthcarePortal.Model.HD_TICKET_ViewModel
@*//karri:#149*@

<div class="row">
    <span class="col-md-3 text-right ">
        @Html.Label("Ticket Status")
    </span>
    <span class="col-md-3 required">
        @Html.Label("Ticket Category")
    </span>
    <span class="col-md-3 text-right ">
        @Html.Label("Ticket Owner")
    </span>
    <span class="col-md-3 required">
       
    </span>
</div>
<div class="row">
    <span class="col-md-3 text-right ">
        
    </span>
    <span class="col-md-3 required">
        @*@Html.DropDownListFor(model => model.CATEGORY, Model.TicketCategoryList, "Select Issue Type", new { @id = "category" })*@
    </span>
    <span class="col-md-3 text-right ">
        @Html.TextBox("ticketowner")
    </span>
    <span class="col-md-3 required">
        <input id="butnSubmit" type="submit" name="agreeOrNot" value="Submit">
    </span>
</div>

HUDHealthcarePortal/Views/HelpDesk/_HelpDeskSubmit - Copy (2).cshtml
@model HUDHealthcarePortal.Model.HD_TICKET_ViewModel
@*//karri:#149*@

<div class="row">
    <span class="col-md-3 text-right ">
        @Html.Label("Ticket Status")
    </span>
    <span class="col-md-3 required">
    @if (Model.TICKET_ID <= 0)
    {
        @Html.DropDownListFor(m => m.STATUS, Model.TicketStatusList, "Ticket Status", new { @id = "status", @disabled = "disabled" })
    }
    else if(Model.IS_HELPDESK_USER != true)
    {
            @Html.DropDownListFor(m => m.STATUS, Model.TicketStatusList, "Ticket Status", new { @id = "status", @disabled = "disabled" })
    }
    else if (Model.IS_HELPDESK_USER == true)
    {
        @Html.DropDownListFor(m => m.STATUS, Model.TicketStatusList, "Ticket Status", new { @id = "status" })
    }
    </span>
    <span class="col-md-3 text-right ">

    </span>
@if (Model.TICKET_ID <= 0)
{
    <span class="col-md-3 required">
        <input id="butnSubmit" type="submit" name="agreeOrNot" value="Submit">
    </span>
}
@if (Model.IS_HELPDESK_USER == true && Model.TICKET_ID > 0 && Model.STATUS != 3)
{
    <span class="col-md-3 required">
        <input id="butnSubmit" type="submit" name="agreeOrNot" value="Update">
    </span>
}
    <span class="col-md-3 required">
        <button type="button" style="color:red;" class="close" data-dismiss="modal">Close</button>
    </span>
</div>

<script type="text/javascript">
    function closeWin()
    {
        window.close();alert();
    }
</script>